# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-pnpm-cache
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache

      - name: 初始化pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: install & build
        run: |
          pnpm install
          pnpm build
          ls public/
  
      # 构建完后先上传到服务器
      - name: scp file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: public/*
          target: /var/www/bingxl.github.io/
          # strip_components: 1
          rm: true

      # 构建完后先上传到服务器
      - name: scp file with trip_components
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
          port: ${{ secrets.PORT }}
          source: public/*
          target: /var/www/scp_file/
          strip_components: 1
          rm: true
      - run: curl -H 'Content-Type:text/plain' --data-binary @source/urls.txt "http://data.zz.baidu.com/urls?site=bingxl.cn&token=TXPxWXjnHVPzbF7b"
      - run: curl -H 'Content-Type:text/plain' --data-binary @source/urls.txt "http://data.zz.baidu.com/urls?site=https://www.bingxl.cn&token=TXPxWXjnHVPzbF7b"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          publish_dir: ./public

   
